version: "3.8"
services:
  service_db_postgres:
    container_name: db_postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ai-finder
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwe123!@#
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    container_name: api_sem
    restart: always 
    command: api
    build: .
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: service_db_postgres
      DB_NAME: ai-finder
      DB_USER: admin
      DB_QDRANT: service_db_qdrant
    volumes:
      - ./LaBSE:/model/LaBSE
    env_file:
      - .env
    depends_on:
      - service_db_postgres
      - service_db_qdrant

  service_db_qdrant:
    container_name: db_qdrant
    image: qdrant/qdrant
    restart: always
    volumes:
      - ./db_apps/qdrant:/qdrant/storage:z
    ports:
      - "6333:6333"
      - "6334:6334"
    
