version: "3.8"
services:
  api:
    restart: always
    container_name: python_sematic_search
    command: api
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: localhost
      DB_NAME: postgres
      DB_USER: postgres
    env_file:
      - .env
    depends_on:
      - service_db_postgres
      - service_db_qdrant

  service_db_postgres:
    container_name: db_postgres
    image: postgres
    restart: always
    volumes:
      - db_apps/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  service_db_qdrant:
    container_name: db_qdrant
    image: qdrant/qdrant
    restart: always
    volumes:
      - db_apps/qdrant:/qdrant/storage:z
    ports:
      - "6333:6333"
      - "6334:6334"
    
