"""empty message

Revision ID: 7d7ac97a3073
Revises: 87ffe1fe1e23
Create Date: 2024-03-14 08:55:25.808035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7ac97a3073'
down_revision: Union[str, None] = '87ffe1fe1e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('role_id_key', 'role', ['id'])
    #op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_unique_constraint('user_id_key', 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_id_key', 'user', type_='unique')
    #op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_constraint('role_id_key', 'role', type_='unique')
    # ### end Alembic commands ###
